name: Notify on Star

on:
  watch:
    types: [started]

jobs:
  notify-telegram:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        uses: EverythingSuckz/github-telegram-notify@main
        with:
          bot_token: ${{ secrets.bot_token }}
          chat_id: -1002951791106
          topic_id : 4
